trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- bash: |
   cat > .env << EOF
   PRODUCT_SERVICE_BASE_URL=https://cgn10niopheyinventory.azurewebsites.net/
   INVENTORY_SERVICE_BASE_URL=https://cgn10niopheyproduct.azurewebsites.net/
   EOF
   displayName: 'Set up DB Connection'

- bash: |
    npm run build
    ls 
  displayName: 'Buidl App'

- task: ArchiveFiles@2
  displayName: 'Archive dist'
  inputs:
    rootFolderOrFile: dist
    includeRootFolder: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '**/*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifatcs: drop'